// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muse.Data;

namespace Muse.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210801011241_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Muse.Models.Twitch.TokenResponse", b =>
                {
                    b.Property<string>("AccessToken")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("Scope")
                        .HasColumnType("longtext");

                    b.Property<string>("TokenType")
                        .HasColumnType("longtext");

                    b.HasKey("AccessToken");

                    b.ToTable("TwitchTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
